name: Application
on:
  push:
    paths:
      - app/**
      - gradle/**
      - gradle*
      - native-packages/packages/**
      - ./*.gradle
  workflow_dispatch:

jobs:
  gradle-wrapper-check:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validation
        uses: gradle/wrapper-validation-action@v3
  terminal-tests:
    name: Run unit tests for terminal emulator
    needs: gradle-wrapper-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Testing terminal emulator library
        run: ./gradlew test
  build-jni:
    name: Build JNI library
    needs: terminal-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        cpu_arch: [aarch64, arm, i686, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lowercase repository name
        run: echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        env:
          ASHELL_BUILDENV_IMAGE_NAME: "ghcr.io/${{ env.REPO_LOWER }}/native-packages-buildenv:latest"
        run: |
          cd native-packages
          find ./jniLibs -type f -delete
          ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.cpu_arch }} qemu-system
      - name: Store JNI library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jni-libs-${{ matrix.cpu_arch }}-${{ github.sha }}
          path: native-packages/jniLibs/*/*.so
          retention-days: 1
  build-debug:
    name: Build debug APK
    needs: build-jni
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JNI library artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: jni-libs-*
          path: native-packages/jniLibs
          merge-multiple: true
      - name: Build
        run: |
          ./gradlew getSystemImage
          ./gradlew assembleDebug
          mkdir -p artifacts
          find ./app/build/outputs/apk/debug -name "*.apk" -exec mv {} ./artifacts/ \;
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ashell-debug-${{ github.sha }}
          path: ./artifacts/*.apk
          retention-days: 1
  build-release:
    name: Build release APK
    needs: build-jni
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JNI library artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: jni-libs-*
          path: native-packages/jniLibs
          merge-multiple: true
      - name: Build
        run: |
          ./gradlew getSystemImage
          ./gradlew assembleRelease
          mkdir -p artifacts
          find ./app/build/outputs/apk/release -name "*.apk" -exec mv {} ./artifacts/ \;
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ashell-release-${{ github.sha }}
          path: ./artifacts/*.apk
          retention-days: 1
  publish:
    name: Publish APKs to Release
    needs: [build-debug, build-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Debug APKs
        uses: actions/download-artifact@v4
        with:
          name: ashell-debug-${{ github.sha }}
          path: artifacts
      - name: Download Release APKs
        uses: actions/download-artifact@v4
        with:
          name: ashell-release-${{ github.sha }}
          path: artifacts
      - name: Publish all to release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_REPLACE: true
