name: Build environment for native packages
on:
  push:
    branches:
      - master
    paths:
      - native-packages/scripts/**
  workflow_dispatch:

jobs:
  update-docker-image:
    name: Update Docker image
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: native-packages/scripts
          tags: ghcr.io/${{ github.repository_owner }}/ashell-buildenv:latest
